version: '3'

volumes:
  pg_data_food:
  static_food:
  media_food:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_food:/var/lib/postgresql/data
  backend:
    image: ridpfrep/food_backend
    env_file: .env
    volumes:
      - static_food:/backend_static
      - media_food:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: ridpfrep/food_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_food:/frontend_static
  gateway:
    image: ridpfrep/food_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static_food:/staticfiles/
      - media_food:/mediafiles/

