version: '3'

volumes:
  pg_data_food:
  static_food:
  media_food:
  redoc:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_food:/var/lib/postgresql/data
  backend:
    image: ridpfrep/food_backend
    # build: ./backend/
    env_file: .env
    volumes:
      - static_food:/backend_static
      - media_food:/app/media
      - redoc:/app/api/docs/
    depends_on:
      - db
  frontend:
    image: ridpfrep/food_frontend
    # build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_food:/frontend_static
  gateway:
    # image: ridpfrep/food_gateway
    image: nginx:1.21.1
    env_file: .env
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_food:/static/
      - media_food:/media/
      - ./frontend/build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/

