# Generated by Django 4.2.1 on 2023-05-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="unit",
            new_name="measurement_unit",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="preparation_time",
            new_name="cooking_time",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="color_code",
            new_name="color",
        ),
    ]
