# Generated by Django 4.2.1 on 2023-05-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_ingredient_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="quantity",
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Вес/количество ингридиента"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(
                verbose_name="Время приготовления в минутах"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                upload_to="recipe/images/", verbose_name="Изображение рецепта"
            ),
        ),
    ]
